# Generated by Django 5.2.14 on 2026-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_attempts', models.IntegerField()),
                ('failed_attempts', models.IntegerField()),
                ('unusual_location', models.BooleanField(default=False)),
                ('vpn_used', models.BooleanField(default=False)),
                ('prediction', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
