# Generated by Django 5.0.6 on 2026-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('failed_logins', models.IntegerField()),
                ('request_rate', models.FloatField()),
                ('unusual_ports', models.IntegerField()),
                ('geo_distance', models.FloatField()),
                ('bot_score', models.FloatField()),
                ('vpn_detected', models.BooleanField(default=False)),
                ('blacklist_hits', models.IntegerField()),
                ('packet_size', models.FloatField()),
                ('predicted_risk', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BatchPrediction',
        ),
        migrations.DeleteModel(
            name='FakeURLPrediction',
        ),
        migrations.DeleteModel(
            name='InteractionPrediction',
        ),
        migrations.DeleteModel(
            name='IPRiskPrediction',
        ),
    ]
