# Generated by Django 5.0.6 on 2026-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_iprecord_delete_batchprediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprecord',
            name='ip_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iprecord',
            name='predicted_risk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='iprecord',
            name='vpn_detected',
            field=models.BooleanField(),
        ),
    ]
