# Generated by Django 5.0.6 on 2026-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0005_alter_iprecord_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprecord',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iprecord',
            name='predicted_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iprecord',
            name='vpn_detected',
            field=models.BooleanField(default=False),
        ),
    ]
