# Generated by Django 5.0.6 on 2026-05-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0006_iprecord_risk_level_alter_iprecord_predicted_risk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeURLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('url_length', models.IntegerField(default=0)),
                ('num_dots', models.IntegerField(default=0)),
                ('uses_https', models.IntegerField(default=0)),
                ('has_ip', models.IntegerField(default=0)),
                ('special_char_count', models.IntegerField(default=0)),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('input_type', models.CharField(choices=[('individual', 'Individual'), ('bulk', 'Bulk')], default='individual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('failed_logins', models.IntegerField(default=0)),
                ('country_risk_score', models.FloatField(default=0.0)),
                ('request_frequency', models.IntegerField(default=0)),
                ('vpn_detected', models.IntegerField(default=0)),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('input_type', models.CharField(choices=[('individual', 'Individual'), ('bulk', 'Bulk')], default='individual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnsafeInteractionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_length', models.IntegerField(default=0)),
                ('suspicious_keywords', models.IntegerField(default=0)),
                ('has_link', models.IntegerField(default=0)),
                ('has_attachment', models.IntegerField(default=0)),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('input_type', models.CharField(choices=[('individual', 'Individual'), ('bulk', 'Bulk')], default='individual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='IPRecord',
        ),
    ]
