# Generated by Django 5.0.6 on 2026-08-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_fakeurlprediction_ipriskprediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_class', models.CharField(max_length=100)),
                ('class_key', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('recommendation', models.TextField()),
                ('confidence', models.FloatField()),
                ('image_thumbnail', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='FakeURLPrediction',
        ),
        migrations.DeleteModel(
            name='IPRiskPrediction',
        ),
        migrations.DeleteModel(
            name='UnsafeInteractionPrediction',
        ),
    ]
