# Generated by Django 5.0.6 on 2026-08-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_scan_delete_fakeurlprediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, default='', max_length=100)),
                ('area_acres', models.FloatField(blank=True, null=True)),
                ('planting_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
