# Generated by Django 5.1.4 on 2025-08-02 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_patient_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('age', models.IntegerField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('symptom_severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10, null=True)),
                ('fatigue_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('mobility_score', models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Mild Difficulty'), (2, 'Moderate Difficulty'), (3, 'Severe Difficulty')], null=True)),
                ('vision_score', models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Blurry'), (2, 'Partially Impaired'), (3, 'Fully Impaired')], null=True)),
                ('diagnosis_code', models.CharField(blank=True, choices=[('G35', 'Multiple Sclerosis'), ('G37', 'Other Demyelinating Diseases'), ('G36', 'Neuromyelitis Optica')], max_length=10, null=True)),
                ('medication', models.CharField(blank=True, choices=[('interferon_beta', 'Interferon Beta'), ('glatiramer_acetate', 'Glatiramer Acetate'), ('natalizumab', 'Natalizumab'), ('ocrelizumab', 'Ocrelizumab')], max_length=50, null=True)),
                ('lab_result_crp', models.CharField(blank=True, choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('low', 'Low')], max_length=10, null=True)),
                ('lab_result_esr', models.CharField(blank=True, choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('low', 'Low')], max_length=10, null=True)),
                ('edss', models.FloatField()),
                ('treatment', models.CharField(max_length=50)),
                ('nii_path', models.TextField()),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relapse_months', models.FloatField(blank=True, null=True)),
                ('estimated_relapse_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
