# Generated by Django 5.1.4 on 2025-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='suggested_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
