# Generated by Django 5.1.4 on 2025-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_predictionhistory_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appetite', models.CharField(choices=[('normal', 'Normal'), ('increased', 'Increased'), ('decreased', 'Decreased')], max_length=20)),
                ('urine_smell', models.CharField(choices=[('normal', 'Normal'), ('sweet', 'Sweet'), ('musty', 'Musty')], max_length=20)),
                ('skin_color', models.CharField(choices=[('normal', 'Normal'), ('light', 'Light'), ('pale', 'Pale')], max_length=20)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('blood_sugar', models.FloatField()),
                ('triglycerides', models.FloatField()),
                ('lactic_acid', models.FloatField()),
                ('crp', models.FloatField(verbose_name='CRP Lab Result')),
                ('esr', models.FloatField(verbose_name='ESR Lab Result')),
                ('flair_file', models.FileField(blank=True, null=True, upload_to='nifti/')),
                ('fatigue', models.BooleanField()),
                ('bone_pain', models.BooleanField()),
                ('seizures', models.BooleanField()),
                ('muscle_weakness', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
