# Generated by Django 5.1.4 on 2025-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_patientinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinput',
            name='confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='estimated_timeline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='relapse_risk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
