# Generated by Django 5.1.4 on 2025-08-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_patientinput_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinput',
            name='spleen_size',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('enlarged', 'Enlarged')], max_length=20, null=True),
        ),
    ]
