# Generated by Django 5.1.4 on 2025-08-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_patientinput_spleen_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinput',
            name='platelet_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
