# Generated by Django 5.1.4 on 2025-08-03 22:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_patientinput_platelet_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinput',
            name='exercise_intolerance',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='Common in mitochondrial or metabolic disorders.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='feeding_difficulty',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='Infants with metabolic disorders often show feeding difficulty.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='neurological_issues',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='PKU, MSUD, and others may manifest neurologically.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='patient_name',
            field=models.CharField(blank=True, help_text='Full name of the patient for identification.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientinput',
            name='vomiting',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='Persistent vomiting may suggest PKU or metabolic crisis.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='appetite',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('increased', 'Increased'), ('decreased', 'Decreased')], help_text='Altered appetite can signal thyroid or metabolic imbalance.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='blood_sugar',
            field=models.FloatField(blank=True, help_text='Random blood sugar (mg/dL). Normal: ~70-140.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Auto-calculated BMI to assess under/overweight status.', null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='bone_pain',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='Common in Gaucher’s disease.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='confidence_score',
            field=models.IntegerField(blank=True, help_text='Model confidence score (0–100).', null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='crp',
            field=models.FloatField(blank=True, help_text='C-reactive protein (inflammation marker). Normal: <5 mg/L.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='CRP Lab Result'),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='esr',
            field=models.FloatField(blank=True, help_text='Erythrocyte sedimentation rate. Normal varies by age/gender.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='ESR Lab Result'),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='fatigue',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='Chronic fatigue may relate to thyroid or mitochondrial issues.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='flair_file',
            field=models.FileField(blank=True, help_text='Upload FLAIR brain scan if available (.nii/.gz).', null=True, upload_to='nifti/'),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='height_cm',
            field=models.FloatField(help_text='Patient height in centimeters (reasonable range: 30-250 cm).', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='lactic_acid',
            field=models.FloatField(blank=True, help_text='Lactic acidosis can suggest mitochondrial disorders. Normal: 0.5–2.2 mmol/L.', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='muscle_weakness',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='Relevant in mitochondrial or metabolic conditions.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='platelet_count',
            field=models.FloatField(blank=True, help_text='Low platelet count may support Gaucher’s diagnosis. Normal: 150–400 × 10^9/L.', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='seizures',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='May indicate neurological/metabolic disorder.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('light', 'Light (May indicate metabolic issue)'), ('pale', 'Pale (Anemia/metabolic disorder)')], help_text='Paleness or light skin could suggest anemia or metabolic disruption.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='spleen_size',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('enlarged', 'Enlarged (Possible Gaucher’s disease)')], help_text='Check for enlarged spleen, especially in Gaucher’s.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='triglycerides',
            field=models.FloatField(blank=True, help_text='Elevated triglycerides may indicate metabolic syndrome.', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='urine_smell',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('sweet', 'Sweet (May indicate MSUD)'), ('musty', 'Musty (PKU indicator)')], help_text='Sweet smell may indicate Maple Syrup Urine Disease. Musty suggests PKU.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientinput',
            name='weight_kg',
            field=models.FloatField(help_text='Patient weight in kilograms (range: 2-250 kg).', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
