# Generated by Django 5.0.3 on 2025-10-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_patientinput_age_patientinput_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinput',
            name='user',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientInput',
        ),
        migrations.DeleteModel(
            name='PredictionHistory',
        ),
    ]
